name: Daily Timetable Email

on:
  schedule:
    - cron: '19 7 * * 1-5'
  workflow_dispatch:  # Allow manual trigger

jobs:
  email-job:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'
          
      - name: Setup Chrome
        uses: browser-actions/setup-chrome@latest
        with:
          chrome-version: stable
          
      - name: Setup ChromeDriver
        uses: nanasess/setup-chromedriver@master

      - name: Cache pip packages
        uses: actions/cache@v3
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Set timezone
        run: |
          sudo timedatectl set-timezone Asia/Kolkata

      - name: Run timetable and email script
        env:
          EMAIL_ADDRESS: ${{ secrets.EMAIL_ADDRESS }}
          RECIPIENT_EMAIL: ${{ secrets.RECIPIENT_EMAIL }}
          EMAIL_PASSWORD: ${{ secrets.EMAIL_PASSWORD }}
          USER_ID: ${{ secrets.USER_ID }}
          PASSWORD_INPUT: ${{ secrets.PASSWORD_INPUT }}
        run: |
          python main.py

